# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c84058ce2489d9f858e165d6c019d397f131b5310b38b499b19c01746d66615cf0bedef402c394b098002526f56c753c227b4bc3b120077d32869396bbd366

test:
  secret_key_base: 57af424ce103cd1ca845d2be855535a30f619d81954b33d5ab3e65436797ef5a7c8f99c95e38ee768a946da3d09ee1bb71f906e60c8a26ee124d12a042770a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
